redhat-developer/intellij-dependency-analytics

build.gradle
gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.0.2

---

gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.0.3

---

gradle.properties

Bump to 0.0.4

---

src/main/resources/META-INF/plugin.xml

Change vendor to make plugin part of the Red Hat organization

---

.github/workflows/IJ.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Add verify workflow

---

build.gradle
src/main/java/org/jboss/tools/intellij/analytics/AnalyticsProcessStreamConnectionProvider.java

Switch to server 0.2.2

---

gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.0.4

---

build.gradle
src/main/java/org/jboss/tools/intellij/analytics/AnalyticsLanguageClient.java
src/main/java/org/jboss/tools/intellij/analytics/AnalyticsLanguageServerDefinition.java
src/main/java/org/jboss/tools/intellij/analytics/AnalyticsPreloadActivity.java
src/main/java/org/jboss/tools/intellij/analytics/AnalyticsProcessStreamConnectionProvider.java
src/main/resources/META-INF/plugin.xml

Switch to ballerina-platform/lsp4intellij library

---

.github/workflows/IJ.yml

Add IntelliJ 2020.3

---

build.gradle
gradle.properties

chore(dep): update LSP to 0.4.20

---

build.gradle
gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.1.0

---

.github/workflows/IJ.yml
gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.1.1

---

src/main/resources/META-INF/plugin.xml

chore: update mimimum to 2020.1 in plugin.xml

---

.github/workflows/IJ.yml
.github/workflows/ci.yml

chore: Switch to main branch

---

Jenkinsfile

chore: auto archive Jenkins release builds

---

gradle.properties
src/main/resources/META-INF/plugin.xml

chore: Prepare for 0.2.0

---

.github/workflows/release.yml

chore: Fix release workflow

---

Jenkinsfile

chore: Report errors

---

.github/workflows/IJ.yml

chore: Add 2021.1

---

.github/workflows/IJ.yml

chore: Add 2021.2

---

.github/workflows/IJ.yml
build.gradle

chore: Run pluginVerifier in the IntelliJ versions workflow

---

build.gradle

chore: update telemetry to 0.0.2.18

---

.github/workflows/release.yml

chore: Switch release job to Java 11

---

gradle.properties
src/main/resources/META-INF/plugin.xml

Signed-off-by: jparsai <jparsai@redhat.com>

chore: Prepare for 0.3.0

---

src/main/java/org/jboss/tools/intellij/stackanalysis/SaReportEditorProvider.java

fix: NPE in SaReportEditorProvider

---

.github/workflows/IJ.yml

build: Add IntelliJ 2021.3

---

.github/workflows/IJ.yml
build.gradle

build: Add IntelliJ 2022.1

---

build.gradle

fix: Use common-compress 1.21

---

build.gradle

fix: Use org.kohsuke:github-api 1.303

---

.github/workflows/release.yml
gradle.properties
src/main/resources/META-INF/plugin.xml

chore(skip-release): Prepare for 0.4.0

---

build.gradle

fix: Update com.fasterxml.jackson.core:jackson-databind

---

src/main/java/org/jboss/tools/intellij/stackanalysis/PreloadCli.java
src/main/java/org/jboss/tools/intellij/stackanalysis/SaAction.java
src/main/java/org/jboss/tools/intellij/stackanalysis/SaProcessExecutor.java

fix: crda not found

---

gradle.properties
src/main/resources/META-INF/plugin.xml

chore(skip-release): Prepare for 0.5.0

---

build.gradle

chore: bump telemetry plugin dependency to 0.0.3.33

---

src/main/java/org/jboss/tools/intellij/analytics/Platform.java
src/main/java/org/jboss/tools/intellij/stackanalysis/Cli.java

chore: bump crda cli from 0.2.4 to 0.2.5

---

.github/workflows/stage.yml
.gitignore

ci: added staging workflow creating early-access releases

---

gradle.properties
src/main/resources/META-INF/plugin.xml

chore(skip-release): prepare for 0.6.0

---

gradle.properties

chore: bump development version to 0.7.0-SNAPSHOT

---

.github/workflows/stage.yml

ci: fixed staging ci

---

Jenkinsfile

ci: add github token to jenkinsfile for consuming crda-java-api

---

src/main/java/org/jboss/tools/intellij/crda/ApiService.java
src/main/java/org/jboss/tools/intellij/stackanalysis/SaAction.java

fix: crda api break function name

---

Jenkinsfile

build: add zgrinber as jenkins release approver

---

src/main/java/org/jboss/tools/intellij/stackanalysis/SaAction.java
src/main/java/org/jboss/tools/intellij/stackanalysis/SaUtils.java

Perform stack analysis asynchronously to avoid UI freezing

fix: perform stack analysis asynchronously to avoid UI freezing

---

build.gradle
src/main/java/org/jboss/tools/intellij/componentanalysis/CAAnnotator.java
src/main/java/org/jboss/tools/intellij/exhort/ApiService.java

report in case there is no TC Recommendation or remediation

fix: add error annotation and link to DA

---

README.md
gradle.properties
src/main/resources/META-INF/plugin.xml

Updated the `README.md` file, and the `change-notes` section in the `plugin.xml` file for an upcoming release.

docs: Updated the readme and change notes for upcoming release

---

README.md

Removed the Snyk related content out of the README.md file.

docs: Removed Snyk references in the README

---

gradle.properties

Prepare the next development iteration.
Bump development version to 1.1.0-SNAPSHOT

chore: bump development version to 1.1.0-SNAPSHOT

---

README.md
src/main/resources/META-INF/plugin.xml

Correct docs for dockerfile scanning

docs: correct docs for dockerfile scanning

---

README.md
src/main/java/org/jboss/tools/intellij/exhort/ApiService.java
src/main/java/org/jboss/tools/intellij/image/ApiService.java

feat: Support http proxy
allow users to configure and use HTTP proxies in the IntelliJ environment.
fixes https://github.com/redhat-developer/intellij-dependency-analytics/issues/177

feat: Support http proxy

---

README.md
build.gradle
src/main/java/org/jboss/tools/intellij/componentanalysis/pnpm/PnpmCAAnnotator.java
src/main/java/org/jboss/tools/intellij/componentanalysis/pnpm/PnpmCAInspection.java
src/main/java/org/jboss/tools/intellij/componentanalysis/pnpm/PnpmCAIntentionAction.java
src/main/java/org/jboss/tools/intellij/exhort/ApiService.java
src/main/java/org/jboss/tools/intellij/settings/ApiSettingsComponent.java
src/main/java/org/jboss/tools/intellij/settings/ApiSettingsConfigurable.java
src/main/java/org/jboss/tools/intellij/settings/ApiSettingsState.java
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/PnpmCAInspection.html

feat: Add support for pnpm package manager
Fixes: https://github.com/redhat-developer/intellij-dependency-analytics/issues/176
This requires https://github.com/trustification/exhort-java-api/pull/133

feat: Add support for pnpm package manager
