redhat-developer/intellij-dependency-analytics

- .github/workflows/conventionalCheck.yml
- .github/workflows/release.yml
> chore: adopt conventional commits

- USAGE_DATA.md
- build.gradle
- src/main/java/org/jboss/tools/intellij/analytics/AnalyticsLanguageClient.java
- src/main/java/org/jboss/tools/intellij/analytics/GitHubReleaseDownloader.java
- src/main/java/org/jboss/tools/intellij/analytics/TelemetryService.java
- src/main/resources/META-INF/plugin.xml
> feat: add telemetry

- src/main/java/org/jboss/tools/intellij/analytics/Platform.java
- src/main/java/org/jboss/tools/intellij/analytics/PreloadLanguageServer.java
- src/main/java/org/jboss/tools/intellij/stackanalysis/SaAction.java
- src/main/resources/META-INF/plugin.xml
Current version of Dependency Analytics IJ Plugin does not support Golang for Component Analysis, as Golang is now supported by CRDA extension we just need to add .mod in allowed extensions rest will be taken case by LSP and CRDA.   
Signed-off-by: jparsai <jparsai@redhat.com>
> feat: Extend support for Golang in Component Analysis.

- .github/workflows/conventionalCheck.yml
- .github/workflows/release.yml
Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
This PR was submitted by a script.
> chore: Pin 3rd-party actions to SHA1

- build.gradle
We target IntelliJ version to major 2021.1 which have been migrated to java 11.
[Supporting article](https://blog.jetbrains.com/platform/2020/09/intellij-project-migrates-to-java-11/?_ga=2.166000830.1812486158.1678029361-235557010.1676467140&_gac=1.24742216.1677670379.CjwKCAiAjPyfBhBMEiwAB2CCIrNHLddgPF1Gc8wcaxG_BF7rAqeReo2N-29QrtLlRjDZQ_OlGTHrXhoCEG8QAvD_BwE&_gl=1*1d5pbom*_ga*MjM1NTU3MDEwLjE2NzY0NjcxNDA.*_ga_9J976DJZ68*MTY3ODI3MzM1MS4zNy4xLjE2NzgyNzM2ODQuNjAuMC4w).
> build: bump java version from 1.8 to 11

- .github/workflows/IJ.yml
Our minimum target version is 2021.1 since https://github.com/redhat-developer/intellij-dependency-analytics/commit/4b67bd4437ad9f12bb913d1ba76b951dd220a4f7.
Based on [this doc](https://docs.google.com/document/d/1dBq4bVlg_r0D7Fp_xu57JepixE2EseNP9hE-Es7fMz8/edit), looks like there was a reason for setting this.
We don't need to test the build process for older versions.
> ci: remove older unsupported version for ci matrix

- src/main/java/org/jboss/tools/intellij/analytics/Settings.java
Storage configuration, file has been deprecated and replaced by value.
[View Doc](https://plugins.jetbrains.com/docs/intellij/persisting-state-of-components.html#defining-the-storage-location).
> chore: the file field in the storage annotation id depercated, replaced by value

- src/main/java/org/jboss/tools/intellij/analytics/GitHubReleaseDownloader.java
- src/main/java/org/jboss/tools/intellij/analytics/PreloadLanguageServer.java
- src/main/java/org/jboss/tools/intellij/stackanalysis/PreloadCli.java
- src/main/resources/META-INF/plugin.xml
Fixes #35, Fixes #76, Fixes #81, Fixes #91, Fixes #92
**Tested locally with versions**:
- 2021.1 (our minimum target)
- 2022.2
- 2022.3 (the latest version)
**Edit 1**:
Looks like this fix, though fixed the issue at hand, introduced a new one.
With this fix, diagnostic is only performed for modifying an already open file, and not for opening one.
**Edit 2**:
The cause for the error described in _Edit 1_ is _lsp4intellij_.
This bug was introduced in version [0.95.1](https://github.com/ballerina-platform/lsp4intellij/releases/tag/0.95.1), and can be demonstrated using the _master-snapshot_ as well.
However, pinning the version to [0.95.0](https://github.com/ballerina-platform/lsp4intellij/releases/tag/0.95.0) resolves this issue.
Pinning the version is handled in #106.
> fix: version 2022.3 breaks by marking PreloadingActivity for internal usage

- .github/workflows/release.yml
> ci: release workflow should run only for semver tags and avoid early-access ones

- .github/workflows/IJ-latest.yml
- .github/workflows/IJ.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/stage.yml
- build.gradle
- src/main/java/org/jboss/tools/intellij/crda/ApiService.java
- src/main/java/org/jboss/tools/intellij/stackanalysis/SaAction.java
> feat: use new backend for java pom manifests stack analysis

- build.gradle
https://docs.gradle.org/current/userguide/dependency_management.html#ex-changing-module-cache-control
> chore: set gradle to always update snapshots version when building

- build.gradle
- src/main/java/org/jboss/tools/intellij/exhort/ApiService.java
- src/main/java/org/jboss/tools/intellij/stackanalysis/SaAction.java
feat: commit of moving stack analysis for npm to new exhort java api artifact.
> feat: commit of moving stack analysis for npm

- gradle.properties
Change gradle.properties' projectVersion to be without suffix of "-SNAPSHOT" in order to enforce jenkins pipeline to release it to the stable channel.
> chore: release Intelli-J dependency analytics version 0.7.0

- build.gradle
- gradle.properties
- src/main/java/org/jboss/tools/intellij/componentanalysis/CAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/CAIntentionAction.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/CAUpdateManifestIntentionAction.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/golang/GoCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/maven/MavenCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/maven/MavenCAUpdateManifestIntentionAction.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/npm/NpmCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/pypi/ce/PipCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/pypi/pro/PipCAAnnotator.java
add CAUpdateManifestIntentionAction mechanism to add an updateManifest annotation, so it will add some general information to manifest from data retrieved from dependencies
and create CAUpdateManifestIntentionAction subclass to add redhat ga repository to pom.xml
> feat: add CAUpdateManifestIntentionAction mechanism to update manifests

- gradle.properties
@zvigrinberg The version is bumped to 1.0.0.
Please review and merge this PR, then we can trigger the release.
> chore(skip-release): prepare for 1.0.0

- src/main/java/org/jboss/tools/intellij/componentanalysis/CAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/CAIntentionAction.java
- src/main/java/org/jboss/tools/intellij/exhort/TelemetryService.java
Added "component_analysis_recommendation_accepted" event to track recommendation acceptance for telemetry. 
Jira: [APPENG-2312](https://issues.redhat.com/browse/APPENG-2312)
> feat: added recommendation acceptance tracking

- src/main/java/org/jboss/tools/intellij/componentanalysis/CAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/CAService.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/Dependency.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/golang/GoCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/gradle/GradleCAAnnotator.java
In case of Applying quick-fix, unless the user save the manifest really quick, there might be inconsistencies and incorrect data caused by the fact that the analysis is invoked with the saved file, which it still doesn't contain on disk the quick-fix version, hence this PR take the change from the cached data document in memory, create a temporary file, and invoke the analysis with it instead of with the original file ( which contains still the vulnerable version  before the quick-fix).
Fixes: https://issues.redhat.com/browse/TC-1631
> fix: TC-1631

- .github/workflows/IJ.yml
- .github/workflows/ci.yml
- build.gradle
- gradle.properties
- src/main/java/org/jboss/tools/intellij/componentanalysis/CAService.java
- src/main/java/org/jboss/tools/intellij/image/ImageReportAction.java
- src/main/java/org/jboss/tools/intellij/stackanalysis/SaAction.java
- src/main/resources/META-INF/plugin.xml
This PR is due to a new error raised in 2024.1.x for `AnAction` Actions in Intelli-J plugin SDK framework:
the IJ version 2024.1.x on latest build brutally deprecated the OLD_EDT ( Old Event Dispatcher Thread)  Action update Thread, with an exception ( No warning to replace it ASAP in logs, but error exception  that stops the plugin from being loaded and function properly), plugins that has actions of kind `AnAction` must explicitly choose in code for each action, whether they use BGT( Background Thread) or EDT thread for update actions  ( the plugin has two actions - Stack Analysis action for invoking analysis and getting HTML report and Image Analysis for invoking the batch analysis on Dockerfile' Base Image ) . 
This PR contains the needed changes to support this change - After that …
> feat: support idea IJ Version 2024.1.x

- .github/workflows/IJ-latest.yml
- .github/workflows/IJ.yml
- .github/workflows/stage.yml
- .gitignore
bump github actions due to upload-artifact deprecation [notice](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md).
> build: bump actions to latest versions

- README.md
- src/main/java/org/jboss/tools/intellij/componentanalysis/CAUtil.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/golang/GoCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/gradle/GradleCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/maven/MavenCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/npm/NpmCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/npm/NpmCAIntentionAction.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/pypi/PipCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/yarn/YarnCAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/yarn/YarnCAInspection.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/yarn/YarnCAIntentionAction.java
- src/main/java/org/jboss/tools/intellij/exhort/ApiService.java
- src/main/java/org/jboss/tools/intellij/settings/ApiSettingsComponent.java
- src/main/java/org/jboss/tools/intellij/settings/ApiSettingsConfigurable.java
- src/main/java/org/jboss/tools/intellij/settings/ApiSettingsState.java
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/YarnCAInspection.html
feat: add support for yarn package manager
Fixes: https://github.com/redhat-developer/intellij-dependency-analytics/issues/175
> feat: add support for yarn package manager

- src/main/java/org/jboss/tools/intellij/exhort/ApiService.java
fix: correct exhortApi.componentAnalysis call parameter
see more info in https://github.com/redhat-developer/intellij-dependency-analytics/issues/188
fix: https://github.com/redhat-developer/intellij-dependency-analytics/issues/188
> fix: correct exhortApi.componentAnalysis call parameter

- src/main/java/org/jboss/tools/intellij/componentanalysis/CAService.java
This is an alternative fix for TC-1631. 
Background: previous fix made in  https://github.com/redhat-developer/intellij-dependency-analytics/pull/161 reading PSI file cached document content from memory and copy it to temp folder for analysis to avoid inconsistent file content between memory and disk while user applies the quickfix and the analysis happens before changes is saved to disk.
However, it causes trouble when we implements some recent features:
e.g. 
- maven wrapper support, it's hard to identify maven wrapper files location as they're not copied to temp folder.
- various JS package managers depends on lock files type, which are also missed in the temp folder.
~Therefore, this is another proposed alternative that allows analysis waits maximum 5 seconds until the memory and disk …
> fix: TC-1631 Explicitly synchronize PSI file cached document content and disk file content to avoid analysis happens before changes is saved to disk.

- README.md
- gradle.properties
- src/main/java/org/jboss/tools/intellij/exhort/ApiService.java
- src/main/java/org/jboss/tools/intellij/settings/ApiSettingsComponent.java
- src/main/java/org/jboss/tools/intellij/settings/ApiSettingsConfigurable.java
- src/main/java/org/jboss/tools/intellij/settings/ApiSettingsState.java
- src/main/java/org/jboss/tools/intellij/settings/MavenSettingsUtil.java
- src/main/resources/META-INF/plugin.xml
feat: Enable using the Maven Wrapper (mvnw)
fixes: https://github.com/redhat-developer/intellij-dependency-analytics/issues/171
related PR: https://github.com/trustification/exhort-java-api/pull/147
> feat: Enable using the Maven Wrapper (mvnw)

- src/main/java/org/jboss/tools/intellij/componentanalysis/CAAnnotator.java
Fixes: https://github.com/redhat-developer/intellij-dependency-analytics/issues/203
fix: allow Inline Vulnerability Severity Alerts level change.
solution verified by QE testing.
> fix: allow Inline Vulnerability Severity Alerts level change.

- README.md
- build.gradle.kts
- gradle/libs.versions.toml
- src/main/java/org/jboss/tools/intellij/componentanalysis/CAAnnotator.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/CAService.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/ExcludeManifestIntentionAction.java
- src/main/java/org/jboss/tools/intellij/componentanalysis/ManifestExclusionManager.java
- src/main/java/org/jboss/tools/intellij/settings/ApiSettingsComponent.java
- src/main/java/org/jboss/tools/intellij/settings/ApiSettingsConfigurable.java
- src/main/java/org/jboss/tools/intellij/settings/ApiSettingsState.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/org/jboss/tools/intellij/componentanalysis/ManifestExclusionManagerSimpleTest.java
feat: Add support for user-configurable patterns/globs for excluding manifests from Component Analysis
This closes https://github.com/redhat-developer/intellij-dependency-analytics/issues/199
Hi @ruromero @Strum355, please review. I make this draft as I don't want to include this in current ongoing 202507 release.
> feat: Add support for user-configurable patterns/globs for excluding manifests from Component Analysis
